#!/usr/bin/env bash
# Bind AgentOS to one or more agent harnesses.
#
# AGENTS.md is the single source of truth. Everything this script writes is a
# GENERATED, DISPOSABLE binding. Never hand-edit a binding — edit AGENTS.md or
# config/, then re-run this script. `bin/os selftest` flags bindings that have
# drifted out of sync.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

KERNEL="AGENTS.md"
MARK="<!-- generated by adapters/install.sh — do not edit; edit AGENTS.md -->"

[ -f "$KERNEL" ] || { echo "adapters: missing $KERNEL at repo root" >&2; exit 1; }

ALL="agents claude kiro cursor copilot windsurf gemini"

usage() {
  cat <<EOF
usage: adapters/install.sh [--all | --list | --detect | <harness>...]

harnesses: $ALL

  --detect   install only for harnesses whose config dir already exists (default)
  --all      install bindings for every supported harness
  --list     show what is currently bound
EOF
}

# Emit frontmatter (\$1, may be empty) + the marker + the full kernel body.
emit() {
  local dest="$1" fm="$2"
  mkdir -p "$(dirname "$dest")"
  { [ -n "$fm" ] && printf '%s\n' "$fm"; printf '%s\n\n' "$MARK"; cat "$KERNEL"; } > "$dest"
  echo "  wrote  $dest"
}

# Relative symlink so the repo stays portable.
link() {
  local dest="$1" target="$2"
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$(realpath --relative-to="$(dirname "$dest")" "$target")" "$dest"
  echo "  link   $dest -> $target"
}

link_skills() {
  local dir="$1"
  mkdir -p "$dir"
  for s in config/skills/*/; do
    [ -d "$s" ] || continue
    link "$dir/$(basename "$s")" "$s"
  done
}

install_agents() {
  echo "agents.md (Codex · Zed · Copilot Workspace · Jules · Devin · opencode)"
  echo "  ok     AGENTS.md is already the native format — nothing to generate"
}

install_claude() {
  echo "claude (Claude Code)"
  emit "CLAUDE.md" ""
  link_skills ".claude/skills"
}

install_kiro() {
  echo "kiro (Kiro IDE · CLI · Web)"
  emit ".kiro/steering/00-kernel.md" "$(printf -- '---\ninclusion: always\n---')"
  link ".kiro/steering/10-vault-conventions.md" "config/steering/10-vault-conventions.md"
  link_skills ".kiro/skills"
  mkdir -p .kiro/hooks
  cat > .kiro/hooks/agentos-boot.json <<'JSON'
{
  "version": "v1",
  "hooks": [
    {
      "name": "AgentOS boot",
      "trigger": "SessionStart",
      "action": { "type": "command", "command": "bash bin/os boot" }
    },
    {
      "name": "AgentOS vault selftest",
      "trigger": "PostFileSave",
      "matcher": "brain/.*\\.md$",
      "action": { "type": "command", "command": "bash bin/os selftest" }
    }
  ]
}
JSON
  echo "  wrote  .kiro/hooks/agentos-boot.json"
}

install_cursor() {
  echo "cursor (Cursor)"
  emit ".cursor/rules/agentos.mdc" \
    "$(printf -- '---\ndescription: AgentOS kernel\nalwaysApply: true\n---')"
}

install_copilot() {
  echo "copilot (GitHub Copilot)"
  emit ".github/copilot-instructions.md" ""
}

install_windsurf() {
  echo "windsurf (Windsurf)"
  emit ".windsurf/rules/agentos.md" \
    "$(printf -- '---\ntrigger: always_on\n---')"
}

install_gemini() {
  echo "gemini (Gemini CLI)"
  emit "GEMINI.md" ""
}

detect() {
  local found="agents"
  [ -d .claude ]   || [ -f CLAUDE.md ]  && found="$found claude"
  [ -d .kiro ]                          && found="$found kiro"
  [ -d .cursor ]                        && found="$found cursor"
  [ -d .github ]                        && found="$found copilot"
  [ -d .windsurf ]                      && found="$found windsurf"
  [ -f GEMINI.md ]                      && found="$found gemini"
  echo "$found"
}

list() {
  printf '%-10s %-46s %s\n' HARNESS BINDING STATUS
  check() {
    if [ -e "$2" ]; then printf '%-10s %-46s %s\n' "$1" "$2" "bound"
    else printf '%-10s %-46s %s\n' "$1" "$2" "-"; fi
  }
  check agents   AGENTS.md
  check claude   CLAUDE.md
  check kiro     .kiro/steering/00-kernel.md
  check cursor   .cursor/rules/agentos.mdc
  check copilot  .github/copilot-instructions.md
  check windsurf .windsurf/rules/agentos.md
  check gemini   GEMINI.md
}

targets=""
case "${1:---detect}" in
  -h|--help) usage; exit 0 ;;
  --list)    list; exit 0 ;;
  --all)     targets="$ALL" ;;
  --detect)  targets="$(detect)" ;;
  *)         targets="$*" ;;
esac

echo "AgentOS · binding kernel from $KERNEL"
echo
for t in $targets; do
  case " $ALL " in
    *" $t "*) "install_$t" ;;
    *) echo "adapters: unknown harness '$t' (known: $ALL)" >&2; exit 1 ;;
  esac
done
echo
echo "done. bindings are generated — re-run after editing AGENTS.md."
